# Generated by Django 6.0.5 on 2026-06-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cartitem_cart_remove_cartitem_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
